/*
 * This source file was generated by the Gradle 'init' task
 */
package cellularfractals;

import cellularfractals.engine.GameLoop;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        GameLoop gameLoop = new GameLoop();
        gameLoop.run();
    }
}
